# Generated by Django 2.1.2 on 2018-11-08 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Neutral')], default=1)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(db_index=True, max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('patient_no', models.CharField(db_index=True, max_length=10, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[(1, 'Ashanti'), (2, 'Brong Ahafo'), (3, 'Central'), (4, 'Eastern'), (5, 'Greater Accra'), (6, 'Nothern'), (7, 'Upper East'), (8, 'Upper West'), (9, 'Volta'), (10, 'Western')])),
                ('patient_type', models.IntegerField(choices=[(1, 'IN'), (2, 'OUT')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patients',
                'db_table': 'patient',
            },
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('patient_no', 'slug')},
        ),
    ]
